In [1]:
import numpy as np
import sys,os
sys.path.append(os.pardir)

import py_func.Deep_learning_torch_func as DL
import py_func.models_func as my_model
import py_func.dat_rb_func as drb
import py_func.my_numpy_class as mnc

In [2]:
import os.path as osp

In [3]:
datapath="../dat/experiment/SLM/fm_6_18"

read=mnc.My_numpy(1, osp.join(datapath, "fm_1_1000_slt0.8_N3_lsd.dat"))
read.simread(3*1000, 1600)
read.data.shape

(3000, 1600)

In [4]:
read.data[2999]

array([ 7, 10,  0, ..., 55, 78, 35])

In [5]:
read2=mnc.My_numpy(1, osp.join(datapath, "fm_1001_6000_slt0.8_N3_lsd.dat"))
read2.simread(3*5000, 1600)
read2.data.shape

(15000, 1600)

In [6]:
read3=mnc.My_numpy(1, osp.join(datapath, "fm_6001_10000_slt0.8_N3_lsd.dat"))
read3.simread(3*4000, 1600)
read3.data.shape

(12000, 1600)

In [7]:
read4=mnc.My_numpy(1, osp.join(datapath, "fm_10001_15000_slt0.8_N3_lsd.dat"))
read4.simread(3*5000, 1600)
read4.data.shape

(15000, 1600)

In [8]:
read5=mnc.My_numpy(1, osp.join(datapath, "fm_15001_20000_slt0.8_N3_lsd.dat"))
read5.simread(3*5000, 1600)
read5.data.shape

(15000, 1600)

In [9]:
read6=mnc.My_numpy(1, osp.join(datapath, "fm_20001_25000_slt0.8_N3_lsd.dat"))
read6.simread(3*5000, 1600)
read6.data.shape

(15000, 1600)

In [10]:
read7=mnc.My_numpy(1, osp.join(datapath, "fm_25001_30000_bfshowslt0.4_N3_lsd.dat"))
read7.simread(3*5000, 1600)
read7.data.shape

(15000, 1600)

In [11]:
read8=mnc.My_numpy(1, osp.join(datapath, "fm_30001_35000_bfshowslt0.4_N3_lsd.dat"))
read8.simread(3*5000, 1600)
read8.data.shape

(15000, 1600)

In [12]:
read9=mnc.My_numpy(1, osp.join(datapath, "fm_35001_45000_bfshowslt0.4_N3_lsd.dat"))
read9.simread(3*10000, 1600)
read9.data.shape

(30000, 1600)

In [13]:
read10=mnc.My_numpy(1, osp.join(datapath, "fm_45001_55000_bfshowslt0.4_N3_lsd.dat"))
read10.simread(3*10000, 1600)
read10.data.shape

(30000, 1600)

In [14]:
read11=mnc.My_numpy(1, osp.join(datapath, "fm_55001_65000_bfshowslt0.4_N3_lsd.dat"))
read11.simread(3*10000, 1600)
read11.data.shape

(30000, 1600)

In [15]:
read12=mnc.My_numpy(1, osp.join(datapath, "fm_65001_70000_bfshowslt0.4_N3_lsd.dat"))
read12.simread(3*5000, 1600)
read12.data.shape

(15000, 1600)

In [16]:
read.data = np.vstack((read.data, read2.data, read3.data, read4.data, read5.data, \
                       read6.data, read7.data, read8.data, read9.data, read10.data, read11.data, read12.data))
read.data.shape

(210000, 1600)

In [17]:
wrb = mnc.My_numpy(1, osp.join(datapath, "fm_1_70000_slt0.4_0.8_N3_lsd.dat"))
wrb.writebin(read.data)

In [18]:
meandata=read.data.reshape(70000,3,1600)
meandata=np.mean(meandata, axis=1)
meandata.shape

(70000, 1600)

In [19]:
wrb2 = mnc.My_numpy(1, osp.join(datapath, "fm_1_70000_slt0.4_0.8_N3_lsd_mean.dat"))
wrb2.writebin(meandata)

In [20]:
middata=read.data.reshape(70000, 3, 1600)[:,1,:]
middata.shape

(70000, 1600)

In [21]:
read.data[0:6]

array([[ 2,  6, 28, ..., 35, 36, 31],
       [ 0,  7, 29, ..., 33, 37, 31],
       [ 1,  6, 29, ..., 34, 41, 34],
       [ 0, 12, 40, ..., 38, 27, 44],
       [ 0,  5, 35, ..., 44, 24, 36],
       [ 0, 12, 23, ..., 51, 22, 21]])

In [22]:
middata[0:2]

array([[ 0,  7, 29, ..., 33, 37, 31],
       [ 0,  5, 35, ..., 44, 24, 36]])

In [23]:
wrb3 = mnc.My_numpy(1, osp.join(datapath, "fm_1_70000_slt0.4_0.8_N3_lsd_midline.dat"))
wrb3.writebin(middata)