In [2]:
import torch
import torch.nn.functional as F
from torch import Tensor
from torch.nn import Module

In [3]:
kernel_size=11
start = (1 - kernel_size) / 2
end = (1 + kernel_size) / 2

In [4]:
start, end

(-5.0, 6.0)

In [5]:
kernel_1d = torch.arange(start, end, step=1, dtype=torch.float)
kernel_1d

tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [7]:
sigma=float(1.5)
kernel_1d = torch.exp(-torch.pow(kernel_1d / sigma, 2) / 2)

In [8]:
kernel_1d

tensor([0.0039, 0.0286, 0.1353, 0.4111, 0.8007, 1.0000, 0.8007, 0.4111, 0.1353,
        0.0286, 0.0039])

In [9]:
kernel_1d = (kernel_1d / kernel_1d.sum()).unsqueeze(dim=0)
kernel_1d

tensor([[0.0010, 0.0076, 0.0360, 0.1094, 0.2130, 0.2660, 0.2130, 0.1094, 0.0360,
         0.0076, 0.0010]])

In [28]:
kernel_1d.shape

torch.Size([1, 11])

In [36]:
a=torch.arange(6).unsqueeze(dim=0)
b=torch.arange(6).unsqueeze(dim=0)
a,b,a.shape

(tensor([[0, 1, 2, 3, 4, 5]]),
 tensor([[0, 1, 2, 3, 4, 5]]),
 torch.Size([1, 6]))

In [39]:
a.sum()

tensor(15)

In [38]:
a.t().shape

torch.Size([6, 1])

In [34]:
c = torch.matmul(a.t(), b)
c

tensor([[ 0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5],
        [ 0,  2,  4,  6,  8, 10],
        [ 0,  3,  6,  9, 12, 15],
        [ 0,  4,  8, 12, 16, 20],
        [ 0,  5, 10, 15, 20, 25]])

In [28]:
kernel_2d = torch.matmul(kernel_1d.t(), kernel_1d)
kernel_2d

tensor([[1.0576e-06, 7.8144e-06, 3.7022e-05, 1.1246e-04, 2.1905e-04, 2.7356e-04,
         2.1905e-04, 1.1246e-04, 3.7022e-05, 7.8144e-06, 1.0576e-06],
        [7.8144e-06, 5.7741e-05, 2.7356e-04, 8.3101e-04, 1.6186e-03, 2.0214e-03,
         1.6186e-03, 8.3101e-04, 2.7356e-04, 5.7741e-05, 7.8144e-06],
        [3.7022e-05, 2.7356e-04, 1.2961e-03, 3.9371e-03, 7.6684e-03, 9.5766e-03,
         7.6684e-03, 3.9371e-03, 1.2961e-03, 2.7356e-04, 3.7022e-05],
        [1.1246e-04, 8.3101e-04, 3.9371e-03, 1.1960e-02, 2.3294e-02, 2.9091e-02,
         2.3294e-02, 1.1960e-02, 3.9371e-03, 8.3101e-04, 1.1246e-04],
        [2.1905e-04, 1.6186e-03, 7.6684e-03, 2.3294e-02, 4.5371e-02, 5.6662e-02,
         4.5371e-02, 2.3294e-02, 7.6684e-03, 1.6186e-03, 2.1905e-04],
        [2.7356e-04, 2.0214e-03, 9.5766e-03, 2.9091e-02, 5.6662e-02, 7.0762e-02,
         5.6662e-02, 2.9091e-02, 9.5766e-03, 2.0214e-03, 2.7356e-04],
        [2.1905e-04, 1.6186e-03, 7.6684e-03, 2.3294e-02, 4.5371e-02, 5.6662e-02,
         4.53

In [29]:
kernel_2d = kernel_2d.expand(3, 1, kernel_size, kernel_size).contiguous()

In [30]:
kernel_2d.shape

torch.Size([3, 1, 11, 11])

In [34]:
x=torch.arange(9,dtype=torch.float).reshape(3,3)
x=x.expand(4,3,3,3).contiguous()

In [35]:
x, x.shape

(tensor([[[[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]]],
 
 
         [[[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]]],
 
 
         [[[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]]],
 
 
         [[[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]],
 
          [[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]]]]),
 torch.Size([4, 3, 3, 3]))

In [36]:
ux = F.conv2d(x, kernel_2d, padding=kernel_size // 2, groups=3)

In [37]:
ux, ux.shape

(tensor([[[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]],
 
 
         [[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]],
 
 
         [[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]],
 
          [[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
        

In [60]:
ux*ux

tensor([[[[1.0324, 1.6990, 1.4410],
          [2.3112, 3.6695, 3.0175],
          [2.4621, 3.8177, 3.0745]],

         [[1.0324, 1.6990, 1.4410],
          [2.3112, 3.6695, 3.0175],
          [2.4621, 3.8177, 3.0745]],

         [[1.0324, 1.6990, 1.4410],
          [2.3112, 3.6695, 3.0175],
          [2.4621, 3.8177, 3.0745]]]])

In [ ]:
ux = F.conv2d(x, kernel_2d, padding=kernel_size // 2, groups=3)
uy = F.conv2d(y, kernel_2d, padding=kernel_size // 2, groups=3)

In [27]:
ux, ux.shape

(tensor([[[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]],
 
 
         [[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]],
 
 
         [[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]],
 
 
         [[[1.0161, 1.3035, 1.2004],
           [1.5203, 1.9156, 1.7371],
           [1.5691, 1.9539, 1.7534]]]]),
 torch.Size([4, 1, 3, 3]))

In [23]:
kernel_2d = kernel_2d.expand(1, 1, kernel_size, kernel_size).contiguous()

In [24]:
kernel_2d.shape

torch.Size([1, 1, 11, 11])

In [25]:
x=torch.arange(9,dtype=torch.float).reshape(3,3)
x=x.expand(4,1,3,3).contiguous()

In [26]:
ux = F.conv2d(x, kernel_2d, padding=kernel_size // 2)

In [40]:
11//2

5

In [41]:
3//2

1

In [42]:
9//3

3